version: '2'
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
services:
  mysql:
    container_name: mysql  
    build:
      context: ./docker/mysql
    env_file: .env
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=root
    networks:
      backend:
        ipv4_address: 172.28.1.1
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$DB_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 20        
  apache_php:
    container_name: apache_php
    build:
      context: ./docker/apache2
      args:
        USER_UID: $DOCKER_USER_UID
        USER_GID: $DOCKER_USER_GID
        USER_NAME: $DOCKER_USER_NAME
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /home/project
    ports:
      - '8080:80'
    networks:
      backend:
        ipv4_address: 172.28.1.2
    volumes:
      - './:/home/project'
  swagger-ui:
    container_name: swagger
    image: swaggerapi/swagger-ui
    volumes:
      - './storage/app/public/api-docs:/app'
    ports:
      - '80'
      - '8085:8080'
    environment:
      - SWAGGER_JSON=/app/api-docs.yaml    